steps:
  - label: "Julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1:
    agents:
      queue: "julia"
      sandbox.jl: "true"
      os: "linux"
    timeout_in_minutes: 60
