steps:
  - label: "Julia v1.6"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
    commands:
      - julia --project=. -e 'using Pkg; Pkg.test()'
    agents:
      queue: "juliacpu"
    timeout_in_minutes: 60
